server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pp_novel
    username: root
    password: 123456789
  data:
    redis:
      host: localhost
      port: 6379
      keyPrefix: "pp_novel:"
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual

sa-token:
  token-name: authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-64
  is-log: true
  token-prefix: Bearer
  is-read-cookie: false

# 邮件配置写在application-local.yml 文件里面，没上传到git

auth:
  register-code: false

s3:
  bucket: bucket
  region: region
  access-key: access-key
  secret-key: secret-key 
  endpoint: domain